using System.Collections;
using Unity.Cinemachine;
using UnityEngine;
using UnityEngine.UI;

[System.Serializable]
public struct CinematicParams
{
    public float Duration;
    public float WorldTimeScale;
    public float OutroDuration;
    public float ZoomAmount;
    public float TransitionSpeed;
    public float ShakeAmplitude;
}
public class CinematicSkillEffect : MonoBehaviour
{
    public float blackBarHeight = 150f;

    private Coroutine _currentCinematicRoutine;
    private Canvas _dynamicCanvas;
    private RectTransform _topBar;
    private RectTransform _bottomBar;
    private float _originalTimeScale;
    private bool _isPlaying = false;

    public void ExecuteCinematic(CinematicParams config, CinemachineCamera activeCam, CinemachineBrain brain, CinemachineImpulseSource impulseSource = null)
    {
        if (_isPlaying)
        {
            StopCoroutine(_currentCinematicRoutine);
            RestoreState(activeCam, 0); // 0 là cờ hiệu không reset FOV
        }
        _currentCinematicRoutine = StartCoroutine(CinematicRoutine(config, activeCam, brain, impulseSource));
    }

    private IEnumerator CinematicRoutine(CinematicParams config, CinemachineCamera activeCam, CinemachineBrain brain, CinemachineImpulseSource impulseSource)
    {
        _isPlaying = true;
        _originalTimeScale = Time.timeScale;
        Time.timeScale = config.WorldTimeScale;

        if (impulseSource != null && config.ShakeAmplitude > 0)
        {
            impulseSource.GenerateImpulse(config.ShakeAmplitude);
        }

        float originalFOV = activeCam.Lens.FieldOfView;
        float currentFOV = originalFOV;

        CreateCinematicUI();

        float timer = 0f;
        while (timer < config.Duration)
        {
            timer += Time.unscaledDeltaTime;
            float remainTime = config.Duration - timer;

            float speed = remainTime > config.OutroDuration ? config.TransitionSpeed : config.TransitionSpeed * 1.5f;
            float targetFOV = remainTime > config.OutroDuration ? (originalFOV - config.ZoomAmount) : originalFOV;

            // Cập nhật UI
            Vector2 targetBarPos = remainTime > config.OutroDuration ? Vector2.zero : new Vector2(0, blackBarHeight);
            UpdateUIBars(targetBarPos, speed);

            // Cập nhật FOV Unity 6
            float t = Time.unscaledDeltaTime * config.TransitionSpeed;
            currentFOV = Mathf.SmoothStep(currentFOV, targetFOV, t);
            activeCam.Lens.FieldOfView = currentFOV;
            if (brain != null)
            {
                brain.ManualUpdate();
            }
            yield return null;
        }
        CameraManager.Instance.ResetBrainUpdateMethod();
        RestoreState(activeCam, originalFOV);
    }

    private void RestoreState(CinemachineCamera activeCam, float originalFOV)
    {
        _isPlaying = false;
        Time.timeScale = _originalTimeScale;

        if (activeCam != null && originalFOV > 0)
            activeCam.Lens.FieldOfView = originalFOV;

        if (_dynamicCanvas != null) Destroy(_dynamicCanvas.gameObject);
    }

    private void UpdateUIBars(Vector2 targetPos, float speed)
    {
        if (_topBar != null) _topBar.anchoredPosition = Vector2.Lerp(_topBar.anchoredPosition, targetPos, Time.unscaledDeltaTime * speed);
        if (_bottomBar != null) _bottomBar.anchoredPosition = Vector2.Lerp(_bottomBar.anchoredPosition, new Vector2(0, -targetPos.y), Time.unscaledDeltaTime * speed);
    }

    private void CreateCinematicUI()
    {
        if (_dynamicCanvas != null) Destroy(_dynamicCanvas.gameObject); // Dọn rác nếu có

        GameObject canvasObj = new GameObject("Cinematic_UI_AutoGenerated");
        _dynamicCanvas = canvasObj.AddComponent<Canvas>();
        _dynamicCanvas.renderMode = RenderMode.ScreenSpaceOverlay;
        _dynamicCanvas.sortingOrder = 999;

        _topBar = CreateBlackBar(canvasObj.transform, "TopBar", new Vector2(0.5f, 1f), new Vector2(0, blackBarHeight));
        _bottomBar = CreateBlackBar(canvasObj.transform, "BottomBar", new Vector2(0.5f, 0f), new Vector2(0, -blackBarHeight));
    }

    private RectTransform CreateBlackBar(Transform parent, string name, Vector2 anchor, Vector2 startPos)
    {
        GameObject barObj = new GameObject(name);
        Image img = barObj.AddComponent<Image>();
        img.color = Color.black;

        RectTransform rect = barObj.GetComponent<RectTransform>();
        rect.SetParent(parent, false);
        rect.anchorMin = new Vector2(0, anchor.y);
        rect.anchorMax = new Vector2(1, anchor.y);
        rect.pivot = anchor;
        rect.sizeDelta = new Vector2(0, blackBarHeight);
        rect.anchoredPosition = startPos;
        return rect;
    }
}